name: CI-CD

on:
  workflow_dispatch:
  push:
    paths-ignore:
    - '**/README.md'
    - 'docs/**'  
  pull_request:
    paths-ignore:
    - '**/README.md'
    - 'docs/**'

jobs:
  build:
    env:
      BUILD_CONFIG: Release

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: NuGet source
      run: |
        dotnet nuget remove source {{cookiecutter.feed_name}}
        dotnet nuget add source https://pkgs.dev.azure.com/{{cookiecutter.organization_name}}/{{ cookiecutter.team_project_name + '/' if cookiecutter.team_project_name != '' else '' }}_packaging/{{cookiecutter.feed_name}}/nuget/v3/index.json --name "{{cookiecutter.feed_name}}" --username "n/a" --password "$env:NUGET_PASSWORD" --store-password-in-clear-text
      shell: pwsh
      env:
      {%- raw %}
        NUGET_PASSWORD:  ${{ secrets.NUGET_PASSWORD }}
      {%- endraw %} 
    - name: Restore dependencies
      run: dotnet restore
    - name: Format
      run: dotnet format --verify-no-changes --no-restore
    - name: Build
      run: dotnet build -c $BUILD_CONFIG --no-restore
    - name: Test
      run: dotnet test -c $BUILD_CONFIG --no-build --verbosity normal
    - name: Package
      run: dotnet pack -c $BUILD_CONFIG src/{{cookiecutter.package_name}}/{{cookiecutter.package_name}}.csproj
    # - name: Upload a Build Artifact
    #   uses: actions/upload-artifact@v2.2.2
    #   with:
    #     path: src/{{cookiecutter.package_name}}/bin/{%- raw %}${{ env.BUILD_CONFIG }}{%- endraw %}
    - name: Get version
      id: version
      run: |
        $version = Get-Content -Path .\src\{{cookiecutter.package_name}}\{{cookiecutter.package_name}}.csproj | Where-Object { $_ -Like "*<Version>*" }
        if ($version) {
            $version = $version.Trim().Substring("<Version>".Length)
            $version = $version.Substring(0, $version.IndexOf("</Version>"))
        }
        else {
            $version = "1.0.0"
        }
        echo "::set-output name=version::$version"
      shell: pwsh
    - name: Publish
      if: github.ref == 'refs/heads/main'
      run: |
        dotnet nuget push .\src\{{cookiecutter.package_name}}\bin\Release\*.nupkg --source "{{cookiecutter.feed_name}}" --api-key n_a --skip-duplicate
      shell: pwsh
      env:
        {%- raw %}
        NUGET_PASSWORD:  ${{ secrets.NUGET_PASSWORD }}
        {%- endraw %}
    - name: Version tag
      if: github.ref == 'refs/heads/main'
      uses: actions/github-script@v3.1.0
      with:
        script: |
          github.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: `refs/tags/${process.env.PACKAGE_VERSION}`,
            sha: context.sha
          })      
      env:
        {%- raw %}
        PACKAGE_VERSION: ${{ steps.version.outputs.version }}
        {%- endraw %}
      continue-on-error: true